export const SET_LOGIN = 'SET_LOGIN'
export const SET_AGENT_LOGIN = 'SET_AGENT_LOGIN'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_SLOT_AMOUNT = 'SET_SLOT_AMOUNT'
export const SET_POINTS = 'SET_POINTS'
export const SET_SIGNAMOUNT = 'SET_SIGNAMOUNT'
export const SET_UET_AMOUNT = 'SET_UET_AMOUNT'
export const SET_LOADINGSTATE = 'SET_LOADINGSTATE'
export const SET_FAVORITE_GAME_LIST = 'SET_FAVORITE_GAME_LIST'
export const SET_UNREAD_MESSAGE = 'SET_UNREAD_MESSAGE'
export const SET_JUAN_DATA = 'SET_JUAN_DATA'
export const SET_IS_SHOW_COMMON_MODULE = 'SET_IS_SHOW_COMMON_MODULE'
export const SET_IS_SHOW_MOBILE_COMMON_MODULE = 'SET_IS_SHOW_MOBILE_COMMON_MODULE'
export const SET_IS_SHOW_LOGIN_DIALOG = 'SET_IS_SHOW_LOGIN_DIALOG'








